events:
- "2020      & 10th & iHack 2020\\\\"
- "2020      & 23rd & NSec CTF 2020\\\\"
- "2019      & 5th & iHack 2019\\\\"
- "2019      & 5th & CS Games Security Challenge\\\\"
- "2018      & 10th & Bsides Ottawa\\\\"
- "2018	     & 3rd & GeekSeek V CTF\\\\"
- "2018	     & 2nd & Hack All The Things 2.0\\\\"
- "2018	     & 2nd & OWASP CTF\\\\"
- "2017	     & 1st & Hack All The Things 1.0\\\\"