links:
 - "GitHub:// \\href{https://github.com/AngelOnFira}{\\custombold{AngelOnFira}}\\\\"
 - "Gitlab:// \\href{https://gitlab.com/AngelOnFira}{\\custombold{AngelOnFira}}\\\\"
 - "LinkedIn://  \\href{https://www.linkedin.com/in/forest-anderson}{\\custombold{forest-anderson}}"